name: ItemsTogether
main: limboba.itemstogether.ItemsTogether
version: 1.0
api-version: 1.13
author: limboBa
commands:
  itemstogether:
    description: Перезагрузить конфигурацию ItemsTogether
    usage: /itemstogether reload
    permission: itemstogether.reload
permissions:
  itemstogether.reload:
    description: Перезагрузка конфига ItemsTogether
    default: op